### ISSUE TITLE
截图功能没出来什么情况- -

### ISSUE THREAD

**Issue by kali3426** [TheKingOfDuck/bcScan#1]
配置好了Selenium，运行完没有截图，生成的报告是空白。状态码.txt是有的，很郁闷

**Comment by kali3426** [comment]
有些200的没截上图也没输出html，是不是需要sleep一下

**Comment by TheKingOfDuck** [comment]
@kali3426 抱歉 一直没注意看issue  可单独运行截图部分的代码试试？这个项目仅出差时无聊写的 没打算更新。
