### ISSUE TITLE
没看到挂马检查的代码呀

### ISSUE THREAD

**Issue by jerrychan807** [TheKingOfDuck/bcScan#2]
怎么判断页面是否被挂马呀?

**Comment by TheKingOfDuck** [comment]
@jerrychan807 emmmmm 这个项目本来就只是出差时打发时间写的 解决同事检查数千个站点时一个一个看的麻烦  至于怎么判断我推荐的是直接看报告中的图片就OK了 如果有空加个检查返回包中关键词的函数也OK 具体懒得去写了。

**Comment by jerrychan807** [comment]
cool,原来开发的出发点是这个~


关键词?比如页面含 博彩等等关键词?

**Comment by TheKingOfDuck** [comment]
对吖 无非就是
```
if keywords in res.text:
       print xxx
else:
        pass
```
的事 懒得收集关键词了 再者很多bc的文字都是以图片的形式存在的或者编码后的 机器不好判断。

**Comment by jerrychan807** [comment]
嗯嗯。这只是其中一种比较直接、简单的判断方式吧。
